### PR TITLE
Improve translations

### PR DESCRIPTION
**Pull request by NathanBnm**
I made some refactor to the `po` translations directory. I removed unused/untranslated files and made metadata separately translatable into the `po/extra` folder to avoid confusion. I refreshed the existing translation files too in order to properly format file header and remove fuzzy strings.

### CODE REVIEW

**Comment by Alecaddd** [comment]
Thank you so much for this.
I'm the first to admit that I don't fully understand how the all l10n is handled by POT files, but shouldn't we keep the empty files to allow users to translate them in their language?
I'm also using Weblate to handle l10n, which reads all the POT files and flags me for the missing translations.

**Comment by NathanBnm** [comment]
It's better not to leave empty translation files. If someone want to add a language then a new file has to be created using the following commands:

`ninja com.github.alecadd.sequeler-update-po`

`ninja extra-update-po`

Didn't know you were using Weblate. Is this project already set up with Weblate?

However if you want to I can work to add a README file to the `po` directory to give instructions on how to create translations and help translators 😊

**Comment by Alecaddd** [comment]
> However if you want to I can work to add a README file to the `po` directory to give instructions on how to create translations and help translators blush

That would be fantastic, thank you so much.
If you can add that to this PR than I'll merge altogether.

And yes, Sequeler is already on Weblate: https://hosted.weblate.org/projects/sequeler/

**Comment by NathanBnm** [comment]
> If you can add that to this PR than I'll merge altogether.
> 
> And yes, Sequeler is already on Weblate: https://hosted.weblate.org/projects/sequeler/


You do not mention this at all in your README so I didn't know it was.

Maybe you'll have to adjust the Weblate config after merging this PR to add both main and metadata translations to it.

**Comment by Alecaddd** [comment]
Indeed, I setup weblate a while ago but since they need to approve FOSS projects for the free tier, that took a couple of months and I forgot to update the Readme.
Anyway, I've also been super busy with Akira so didn't give the deserved attention to either Sequeler or Taxi :sweat:

**Comment by NathanBnm** [comment]
@Alecaddd it's fine, Akira is a really great project too!

When you'll have time could you just update the Weblate config in order to add the `po/extra` folder to translations? I think you can add the "Add a language" button which is not appearing yet.

> However if you want to I can work to add a README file to the `po` directory to give instructions on how to create translations and help translators

Are you still interested about this? I can do another PR

**Comment by Alecaddd** [comment]
I'm trying to find how to do that but I can't seem to find it.
Also, I updated the Italian translation but the `Commit` command doesn't seem to work.

**Comment by Alecaddd** [comment]
It seems like I'm not able to that with my free plan.
I can't add another component and I can't add an SSH key to push translated string to my repo.
Well, that's annoying.

**Comment by NathanBnm** [comment]
> It seems like I'm not able to that with my free plan.
> I can't add another component and I can't add an SSH key to push translated string to my repo.
> Well, that's annoying.

This Is surprising, I was sure that for open source projects it was all included for free. Maybe you can consider to reach them about that. I even saw some not maintained anymore projects with these features, I would be surprised if they had a subscription. This is strange 🤔

**Comment by Alecaddd** [comment]
Yeah, I wrote them an email, meanwhile I'm going through their docs, which are not great and kinda confusing.

**Comment by Alecaddd** [comment]
All right, I was missing an access token in order to push the new strings from weblate to the github repo.
That's fixed now and it's possible to add new languages in the web interface.
To create a new component for `po/extra` I need to contact them and they need to approve it.

**Comment by NathanBnm** [comment]
@Alecaddd I just saw https://gitlocalize.com/ maybe you could be interested. I don't know if it's great or not I never tried. But it seems to be free and integrates with GitHub.

**Comment by Alecaddd** [comment]
@NathanBnm yeah, they actually contacted me a week ago asking for a video review.
I'll see how it works and consider switching. It's weird that is completely free tho :sweat_smile:

**Comment by NathanBnm** [comment]
@Alecaddd it's new right? Never heard about it before. Maybe they're free to start their business and to be known before offering paid plans later. Would be great if it stays free for open source projects at least.

**Pull request merged**
