### PR TITLE
Validate appdata & desktop file

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Still not sure why you install the same icon in the mimetypes directory.

**Comment by Alecaddd** [comment]
That's a leftover from the beginning of time when I was thinking about having some sort of dedicated sequeler files to store connections. A pretty silly idea.

**Comment by bilelmoussaoui** [comment]
Well, that should be removed than :+1:

**Comment by Alecaddd** [comment]
Yup, I'm doing it already :smile:

**Pull request merged**
