### PR TITLE
Adding entry for custom port connection

### PR DESCRIPTION
**Pull request by caioguedes**
I made a simple implementation for #38. Please, check out. If you need more changes, let me know!

Thanks!

### CODE REVIEW

**Comment by Alecaddd** [comment]
Did you compile it and test it with an actual DB?
I had the same implementation before releasing the app, but I had to drop it because `lbgda` wasn't recognizing the PORT attribute.

**Comment by Alecaddd** [comment]
Also, be sure the app doesn't freezes/crash when you specify a wrong port

**Comment by caioguedes** [comment]
Yep, compiled and tested. The port number is recognizing well, if you pass a wrong port like characters, this will be ignored by `ligbda` or if you keep it blank, `libgda` takes the default port. I'm working on port field to limit type hints for only digits.

**Comment by Alecaddd** [comment]
@caioguedes awesome news, thank you so much for your help.
How about the UI freezing when the port is incorrect? I'm trying to overcome this issue by turning all the DB related methods into `async` methods.
Let me know if you encountered the same issue.

**Pull request merged**
